### ISSUE TITLE
trpc as a separate package 

### ISSUE THREAD

**Issue by somu-code** [Hiperultimate/monorepo-template#2]
Is it better to declare trpc as a separate package in packages directory instead of installing them separately in multiple apps.

**Comment by Hiperultimate** [comment]
It depends on the requirement but in a situation where you have a monorepo which has more than 1 app plus they want to use trpc then it is better to declare trpc in its own package. Setting it up for different technologies might be a bit different and you will require trpc package to export specific built in trpc methods accordingly but in the long run it helps in reusing the code. And in that way you can write procedures once and use it in different applications as well.

**Comment by Hiperultimate** [comment]
@somu-code It depends on the requirement but in a situation where you have a monorepo which has more than 1 app plus they want to use trpc then it is better to declare trpc in its own package. Setting it up for different technologies might be a bit different and you will require trpc package to export specific built in trpc methods accordingly but in the long run it helps in reusing the code.  And in that way you can write procedures once and use it in different applications as well.
